### ISSUE TITLE
How did you manage to get FontAwesome working in Urxvt

### ISSUE THREAD

**Issue by sevaho** [autophagy/antimber#1]
This is more like a question than an issue.

I see in your screenshot that you got FontAwesome working in your right terminal, is this Urxvt and if so how did you manage to get it working?

Greetings

**Comment by autophagy** [comment]
Hi! The icons in the right terminal aren't from FontAwesome, they're from [DejaVu Sans Mono for Powerline](https://github.com/powerline/fonts/tree/master/DejaVuSansMono) for use with [vim-powerline](https://github.com/powerline/powerline). I tried to play around with the fallback fonts to see if I could get FontAwesome to work, but it seems to be an [ongoing issue](https://github.com/FortAwesome/Font-Awesome/issues/3681) I'm afraid :disappointed:

**Comment by sevaho** [comment]
Yeah have the same issue with urxvt thought you had it figured out, well I'll try them fonts thank you!

**Comment by dhruvinsh** [comment]
hope this help: https://github.com/FortAwesome/Font-Awesome/issues/3681#issuecomment-478277810

basically nerd font has font awesome in it, so it works
